





#define EEPROM_VENDOR_NAME_SIZE                       32
#define EEPROM_PRODUCT_CODE_SIZE                      32
#define EEPROM_REVISION_NUMBER_SIZE                   32
#define EEPROM_METER_NAME_SIZE                        32
#define EEPROM_MODEL_SIZE                             32
#define EEPROM_MANUFACTURER_SIZE                      32
#define EEPROM_SERIAL_NO_SIZE                         32
#define EEPROM_HARDWARE_REV_SIZE                      16
#define EEPROM_FIRMWARE_VER_SIZE                      32
#define EEPROM_MAC_ADD_SIZE							  32
#define EEPROM_NODE_SIZE							  32
#define EEPROM_NODE_ID_SIZE							  2





//=========================================================================================================================

#define EEPROM_ESID_SIZE                        32
#define EEPROM_EPASS_SIZE                       64
#define EEPROM_EMON_API_KEY_SIZE                33
#define EEPROM_EMON_SERVER_SIZE                 32
#define EEPROM_EMON_PATH_SIZE                   16
#define EEPROM_EMON_NODE_SIZE                   32
#define EEPROM_MQTT_SERVER_SIZE                 32
#define EEPROM_MQTT_TOPIC_SIZE                  32
#define EEPROM_MQTT_USER_SIZE                   32
#define EEPROM_MQTT_PASS_SIZE                   64
#define EEPROM_EMON_FINGERPRINT_SIZE            60
#define EEPROM_MQTT_FEED_PREFIX_SIZE            10
#define EEPROM_WWW_USER_SIZE                    16
#define EEPROM_WWW_PASS_SIZE                    16
#define EEPROM_CAL_VOLTAGE_SIZE                 6
#define EEPROM_CAL_CT1_SIZE                     6
#define EEPROM_CAL_CT2_SIZE                     6
#define EEPROM_CAL_FREQ_SIZE                    6
#define EEPROM_CAL_GAIN_SIZE                    6


//Devise Calibration Data
#define EEPROM_VOLTAGESAGTHRESHOLD_SIZE               16
#define EEPROM_L_LINECALIBRATIONGAIN_SIZE             16
#define EEPROM_L_LINECALIBRATIONANGLE_SIZE            16
#define EEPROM_N_LINECALIBRATIONGAIN_SIZE             16
#define EEPROM_N_LINECALIBRATIONANGLE_SIZE            16
#define EEPROM_ACTIVESTARTUPPOWERTHRESHOLD_SIZE       16
#define EEPROM_ACTIVENOLOADPOWERTHRESHOLD_SIZE        16
#define EEPROM_REACTIVESTARTUPPOWERTHRESHOLD_SIZE     16
#define EEPROM_REACTIVENOLOADPOWERTHRESHOLD_SIZE      16
#define EEPROM_MEASUREMENTCALIBRATIONSTART_SIZE       16
#define EEPROM_VOLTAGERMSGAIN_SIZE                    16
#define EEPROM_L_LINECURRENTRMSGAIN_SIZE              16
#define EEPROM_N_LINECURRENTRMSGAIN_SIZE              16
#define EEPROM_VOLTAGEOFFSET_SIZE                     16
#define EEPROM_L_LINECURRENTOFFSET_SIZE               16
#define EEPROM_N_LINECURRENTOFFSET_SIZE               16
#define EEPROM_L_LINEACTIVEPOWEROFFSET_SIZE           16
#define EEPROM_L_LINEREACTIVEPOWEROFFSET_SIZE         16
#define EEPROM_N_LINEACTIVEPOWEROFFSET_SIZE           16
#define EEPROM_N_LINEREACTIVEPOWEROFFSET_SIZE         16
#define EEPROM_CHECKSUM1_SIZE                         16
#define EEPROM_CHECKSUM2_SIZE                         16
#define EEPROM_METERINGMODECONFIGURATION_SIZE         16



//Devise Measuring and Energy Data
#define EEPROM_FORWARDACTIVEENERGY_SIZE                             16
#define EEPROM_REVERSEACTIVEENERGY_SIZE                             16
#define EEPROM_ABSOLUTEACTIVEENERGY_SIZE                            16
#define EEPROM_FORWARD_INDUCTIVEREACTIVEENERGY_SIZE                 16
#define EEPROM_REVERSE_CAPACITIVEREACTIVEENERGY_SIZE                16
#define EEPROM_ABSOLUTEREACTIVEENERGY_SIZE                          16
#define EEPROM_METERINGSTATUS_SIZE                                  16
#define EEPROM_L_LINECURRENTRMS_SIZE                                16
#define EEPROM_VOLTAGERMS_SIZE                                      16
#define EEPROM_L_LINEMEANACTIVEPOWER_SIZE                           16
#define EEPROM_L_LINEMEANREACTIVEPOWER_SIZE                         16
#define EEPROM_VOLTAGEFREQUENCY_SIZE                                16
#define EEPROM_L_LINEPOWERFACTOR_SIZE                               16
#define EEPROM_PHASEANGLEBETWEENVOLTAGEANDL_LINECURRENT_SIZE        16
#define EEPROM_L_LINEMEANAPPARENTPOWER_SIZE                         16
#define EEPROM_N_LINECURRENTRMS_SIZE                                16
#define EEPROM_N_LINEMEANACTIVEPOWER_SIZE                           16
#define EEPROM_N_LINEMEANREACTIVEPOWER_SIZE                         16
#define EEPROM_N_LINEPOWERFACTOR_SIZE                               16
#define EEPROM_PHASEANGLEBETWEENVOLTAGEANDN_LINECURRENT_SIZE        16
#define EEPROM_N_LINEMEANAPPARENTPOWER_SIZE                         16
#define EEPROM_TEMPERATURE_SIZE										16
#define EEPROM_TEMPERATURE_F_SIZE									16
#define EEPROM_HUMIDITY_SIZE										16
#define EEPROM_HEATINDEX_TEMP_SIZE									16
#define EEPROM_HEATINDEX_HUM_SIZE									16




#ifdef SOLAR_METER
#define EEPROM_CAL_SVOLTAGE_SIZE  6
#define EEPROM_CAL_SCT1_SIZE      6
#define EEPROM_CAL_SCT2_SIZE      6
#endif
#define EEPROM_SIZE               8192

#define EEPROM_VENDOR_NAME_SIZE                       32
#define EEPROM_PRODUCT_CODE_SIZE                      32
#define EEPROM_REVISION_NUMBER_SIZE                   32
#define EEPROM_METER_NAME_SIZE                        32
#define EEPROM_MODEL_SIZE                             32
#define EEPROM_MANUFACTURER_SIZE                      32
#define EEPROM_SERIAL_NO_SIZE                         32
#define EEPROM_HARDWARE_REV_SIZE                      16
#define EEPROM_FIRMWARE_VER_SIZE                      32
#define EEPROM_MAC_ADD_SIZE							  32
#define EEPROM_NODE_SIZE							  32
#define EEPROM_NODE_ID_SIZE							  32


#define EEPROM_VENDOR_NAME_START         0
#define EEPROM_VENDOR_NAME_END           (EEPROM_VENDOR_NAME_START + EEPROM_VENDOR_NAME_SIZE)
#define EEPROM_PRODUCT_CODEE_START         EEPROM_VENDOR_NAME_END
#define EEPROM_PRODUCT_CODE_END           (EEPROM_PRODUCT_CODEE_START + EEPROM_PRODUCT_CODE_SIZE)
#define EEPROM_REVISION_NUMBER_START         EEPROM_PRODUCT_CODE_END
#define EEPROM_REVISION_NUMBER_END           (EEPROM_REVISION_NUMBER_START + EEPROM_REVISION_NUMBER_SIZE)
#define EEPROM_METER_NAME_START         EEPROM_REVISION_NUMBER_END
#define EEPROM_METER_NAME_END           (EEPROM_METER_NAME_START + EEPROM_METER_NAME_SIZE)
#define EEPROM_MODEL_START         EEPROM_METER_NAME_END
#define EEPROM_MODEL_END           (EEPROM_MODEL_START + EEPROM_MODEL_SIZE)
#define EEPROM_MANUFACTURER_START         EEPROM_MODEL_END
#define EEPROM_MANUFACTURER_END           (EEPROM_MANUFACTURER_START + EEPROM_MANUFACTURER_SIZE)
#define EEPROM_SERIAL_NO_START         EEPROM_MANUFACTURER_END
#define EEPROM_SERIAL_NO_END           (EEPROM_SERIAL_NO_START + EEPROM_SERIAL_NO_SIZE)
#define EEPROM_HARDWARE_REV_START         EEPROM_SERIAL_NO_END
#define EEPROM_HARDWARE_REV_END           (EEPROM_HARDWARE_REV_START + EEPROM_HARDWARE_REV_SIZE)
#define EEPROM_FIRMWARE_VER_START         EEPROM_HARDWARE_REV_END
#define EEPROM_FIRMWARE_VER_END           (EEPROM_FIRMWARE_VER_START + EEPROM_FIRMWARE_VER_SIZE)
#define EEPROM_MAC_ADD_START         EEPROM_FIRMWARE_VER_END
#define EEPROM_MAC_ADD_END           (EEPROM_MAC_ADD_START + EEPROM_MAC_ADD_SIZE)
#define EEPROM_NODE_START         EEPROM_MAC_ADD_END
#define EEPROM_NODE_END           (EEPROM_NODE_START + EEPROM_NODE_SIZE)
#define EEPROM_NODE_ID_START         EEPROM_NODE_END
#define EEPROM_NODE_ID_END           (EEPROM_NODE_ID_START + EEPROM_NODE_ID_SIZE)

#define EEPROM_ESID_START         (EEPROM_NODE_ID_END+5)
#define EEPROM_ESID_END           (EEPROM_ESID_START + EEPROM_ESID_SIZE)
#define EEPROM_EPASS_START        EEPROM_ESID_END
#define EEPROM_EPASS_END          (EEPROM_EPASS_START + EEPROM_EPASS_SIZE)
#define EEPROM_EMON_API_KEY_START EEPROM_EPASS_END
#define EEPROM_EMON_API_KEY_END   (EEPROM_EMON_API_KEY_START + EEPROM_EMON_API_KEY_SIZE)
#define EEPROM_EMON_SERVER_START  EEPROM_EMON_API_KEY_END
#define EEPROM_EMON_SERVER_END    (EEPROM_EMON_SERVER_START + EEPROM_EMON_SERVER_SIZE)
#define EEPROM_EMON_NODE_START    EEPROM_EMON_SERVER_END
#define EEPROM_EMON_NODE_END      (EEPROM_EMON_NODE_START + EEPROM_EMON_NODE_SIZE)
#define EEPROM_MQTT_SERVER_START  EEPROM_EMON_NODE_END
#define EEPROM_MQTT_SERVER_END    (EEPROM_MQTT_SERVER_START + EEPROM_MQTT_SERVER_SIZE)
#define EEPROM_MQTT_TOPIC_START   EEPROM_MQTT_SERVER_END
#define EEPROM_MQTT_TOPIC_END     (EEPROM_MQTT_TOPIC_START + EEPROM_MQTT_TOPIC_SIZE)
#define EEPROM_MQTT_USER_START    EEPROM_MQTT_TOPIC_END
#define EEPROM_MQTT_USER_END      (EEPROM_MQTT_USER_START + EEPROM_MQTT_USER_SIZE)
#define EEPROM_MQTT_PASS_START    EEPROM_MQTT_USER_END
#define EEPROM_MQTT_PASS_END      (EEPROM_MQTT_PASS_START + EEPROM_MQTT_PASS_SIZE)
#define EEPROM_EMON_FINGERPRINT_START  EEPROM_MQTT_PASS_END
#define EEPROM_EMON_FINGERPRINT_END    (EEPROM_EMON_FINGERPRINT_START + EEPROM_EMON_FINGERPRINT_SIZE)
#define EEPROM_MQTT_FEED_PREFIX_START  EEPROM_EMON_FINGERPRINT_END
#define EEPROM_MQTT_FEED_PREFIX_END    (EEPROM_MQTT_FEED_PREFIX_START + EEPROM_MQTT_FEED_PREFIX_SIZE)
#define EEPROM_WWW_USER_START     EEPROM_MQTT_FEED_PREFIX_END
#define EEPROM_WWW_USER_END       (EEPROM_WWW_USER_START + EEPROM_WWW_USER_SIZE)
#define EEPROM_WWW_PASS_START     EEPROM_WWW_USER_END
#define EEPROM_WWW_PASS_END       (EEPROM_WWW_PASS_START + EEPROM_WWW_PASS_SIZE)
#define EEPROM_EMON_PATH_START    EEPROM_WWW_PASS_END
#define EEPROM_EMON_PATH_END      (EEPROM_EMON_PATH_START + EEPROM_EMON_PATH_SIZE)
#define EEPROM_CAL_VOLTAGE_START  EEPROM_EMON_PATH_END
#define EEPROM_CAL_VOLTAGE_END    (EEPROM_CAL_VOLTAGE_START + EEPROM_CAL_VOLTAGE_SIZE)
#define EEPROM_CAL_CT1_START   EEPROM_CAL_VOLTAGE_END
#define EEPROM_CAL_CT1_END     (EEPROM_CAL_CT1_START + EEPROM_CAL_CT1_SIZE)
#define EEPROM_CAL_CT2_START    EEPROM_CAL_CT1_END
#define EEPROM_CAL_CT2_END      (EEPROM_CAL_CT2_START + EEPROM_CAL_CT2_SIZE)
#define EEPROM_CAL_FREQ_START    EEPROM_CAL_CT2_END
#define EEPROM_CAL_FREQ_END      (EEPROM_CAL_FREQ_START + EEPROM_CAL_FREQ_SIZE)
#define EEPROM_CAL_GAIN_START    EEPROM_CAL_FREQ_END
#define EEPROM_CAL_GAIN_END      (EEPROM_CAL_GAIN_START + EEPROM_CAL_GAIN_SIZE)

#define EEPROM_VOLTSAGTH_START    EEPROM_CAL_GAIN_END+5
#define EEPROM_VOLTSAGTH_END      (EEPROM_VOLTSAGTH_START + EEPROM_VOLTAGESAGTHRESHOLD_SIZE)
#define EEPROM_L_Line_CAL_GAIN_START    EEPROM_VOLTSAGTH_END
#define EEPROM_L_Line_CAL_GAIN_END      (EEPROM_L_Line_CAL_GAIN_START + EEPROM_L_LINECALIBRATIONGAIN_SIZE)
#define EEPROM_L_Line_CAL_ANG_START    EEPROM_L_Line_CAL_GAIN_END
#define EEPROM_L_Line_CAL_ANG_END      (EEPROM_L_Line_CAL_ANG_START + EEPROM_L_LINECALIBRATIONANGLE_SIZE)
#define EEPROM_N_Line_CAL_GAIN_START    EEPROM_L_Line_CAL_ANG_END
#define EEPROM_N_Line_CAL_GAIN_END      (EEPROM_N_Line_CAL_GAIN_START + EEPROM_N_LINECALIBRATIONGAIN_SIZE)
#define EEPROM_N_Line_CAL_ANG_START    EEPROM_N_Line_CAL_GAIN_END
#define EEPROM_N_Line_CAL_ANG_END      (EEPROM_N_Line_CAL_ANG_START + EEPROM_N_LINECALIBRATIONANGLE_SIZE)
#define EEPROM_ACT_STUP_PWRTH_START    EEPROM_N_Line_CAL_ANG_END
#define EEPROM_ACT_STUP_PWRTH_END      (EEPROM_ACT_STUP_PWRTH_START + EEPROM_ACTIVESTARTUPPOWERTHRESHOLD_SIZE)
#define EEPROM_ACT_NOLOAD_PWRTH_START    EEPROM_ACT_STUP_PWRTH_END
#define EEPROM_ACT_NOLOAD_PWRTH_END      (EEPROM_ACT_NOLOAD_PWRTH_START + EEPROM_ACTIVENOLOADPOWERTHRESHOLD_SIZE)
#define EEPROM_REACT_STUP_PWRTH_START    EEPROM_ACT_NOLOAD_PWRTH_END
#define EEPROM_REACT_STUP_PWRTH_END      (EEPROM_REACT_STUP_PWRTH_START + EEPROM_REACTIVESTARTUPPOWERTHRESHOLD_SIZE)
#define EEPROM_REACT_NOLOAD_PWRTH_START    EEPROM_REACT_STUP_PWRTH_END
#define EEPROM_REACT_NOLOAD_PWRTH_END      (EEPROM_REACT_NOLOAD_PWRTH_START + EEPROM_REACTIVENOLOADPOWERTHRESHOLD_SIZE)
#define EEPROM_MESUR_CAL_START              EEPROM_REACT_NOLOAD_PWRTH_END
#define EEPROM_RMESUR_CAL_END      (EEPROM_MESUR_CAL_START + EEPROM_MEASUREMENTCALIBRATIONSTART_SIZE)
#define EEPROM_VOL_GAIN_START    EEPROM_RMESUR_CAL_END
#define EEPROM_VOL_GAIN_END      (EEPROM_VOL_GAIN_START + EEPROM_VOLTAGERMSGAIN_SIZE)
#define EEPROM_L_LINE_CUR_RMSGAIN_START    EEPROM_VOL_GAIN_END
#define EEPROM_L_LINE_CUR_RMSGAIN_END      (EEPROM_L_LINE_CUR_RMSGAIN_START + EEPROM_L_LINECURRENTRMSGAIN_SIZE)
#define EEPROM_N_LINE_CUR_RMSGAIN_START    EEPROM_L_LINE_CUR_RMSGAIN_END
#define EEPROM_N_LINE_CUR_RMSGAIN_END      (EEPROM_N_LINE_CUR_RMSGAIN_START + EEPROM_N_LINECURRENTRMSGAIN_SIZE)
#define EEPROM_VOLT_OFFSET_START    EEPROM_N_LINE_CUR_RMSGAIN_END
#define EEPROM_VOLT_OFFSET_END      (EEPROM_VOLT_OFFSET_START + EEPROM_VOLTAGEOFFSET_SIZE)
#define EEPROM_L_LINE_CUR_OFFSET_START    EEPROM_VOLT_OFFSET_END
#define EEPROM_L_LINE_CUR_OFFSET_END      (EEPROM_L_LINE_CUR_OFFSET_START + EEPROM_L_LINECURRENTOFFSET_SIZE)
#define EEPROM_N_LINE_CUR_OFFSET_START    EEPROM_L_LINE_CUR_OFFSET_END
#define EEPROM_N_LINE_CUR_OFFSET_END      (EEPROM_N_LINE_CUR_OFFSET_START + EEPROM_N_LINECURRENTOFFSET_SIZE)
#define EEPROM_L_LINE_ACT_PWR_OFFSET_START    EEPROM_N_LINE_CUR_OFFSET_END
#define EEPROM_L_LINE_ACT_PWR_OFFSET_END      (EEPROM_L_LINE_ACT_PWR_OFFSET_START + EEPROM_L_LINEACTIVEPOWEROFFSET_SIZE)
#define EEPROM_L_LINE_REACT_PWR_OFFSET_START    EEPROM_L_LINE_ACT_PWR_OFFSET_END
#define EEPROM_L_LINE_REACT_PWR_OFFSET_END      (EEPROM_L_LINE_REACT_PWR_OFFSET_START + EEPROM_L_LINEREACTIVEPOWEROFFSET_SIZE)
#define EEPROM_N_LINE_ACT_PWR_OFFSET_START    EEPROM_L_LINE_REACT_PWR_OFFSET_END
#define EEPROM_N_LINE_ACT_PWR_OFFSET_END      (EEPROM_N_LINE_ACT_PWR_OFFSET_START + EEPROM_N_LINEACTIVEPOWEROFFSET_SIZE)
#define EEPROM_N_LINE_REACT_PWR_OFFSET_START    EEPROM_N_LINE_ACT_PWR_OFFSET_END
#define EEPROM_N_LINE_REACT_PWR_OFFSET_END      (EEPROM_N_LINE_REACT_PWR_OFFSET_START + EEPROM_N_LINEREACTIVEPOWEROFFSET_SIZE)
#define EEPROM_CHECKSUM1_START    EEPROM_N_LINE_REACT_PWR_OFFSET_END
#define EEPROM_CHECKSUM1_END      (EEPROM_CHECKSUM1_START + EEPROM_CHECKSUM1_SIZE)
#define EEPROM_CHECKSUM2_START    EEPROM_CHECKSUM1_END
#define EEPROM_CHECKSUM2_END      (EEPROM_CHECKSUM2_START + EEPROM_CHECKSUM2_SIZE)
#define EEPROM_METER_MODE_CONFIG_START    EEPROM_CHECKSUM2_END
#define EEPROM_METER_MODE_CONFIG_END      (EEPROM_METER_MODE_CONFIG_START + EEPROM_METERINGMODECONFIGURATION_SIZE)


#define EEPROM_FWD_ACT_ENERGY_START    EEPROM_METER_MODE_CONFIG_END+5
#define EEPROM_FWD_ACT_ENERGY_END      (EEPROM_FWD_ACT_ENERGY_START + EEPROM_FORWARDACTIVEENERGY_SIZE)
#define EEPROM_RWS_ACT_ENERGY_START    EEPROM_FWD_ACT_ENERGY_END
#define EEPROM_RWS_ACT_ENERGY_END      (EEPROM_RWS_ACT_ENERGY_START + EEPROM_REVERSEACTIVEENERGY_SIZE)
#define EEPROM_ABS_ACT_ENERGY_START    EEPROM_RWS_ACT_ENERGY_END
#define EEPROM_ABS_ACT_ENERGY_END      (EEPROM_ABS_ACT_ENERGY_START + EEPROM_ABSOLUTEACTIVEENERGY_SIZE)
#define EEPROM_FWD_INDREACT_EENERGY_START    EEPROM_ABS_ACT_ENERGY_END
#define EEPROM_FWD_INDREACT_EENERGY_END      (EEPROM_FWD_INDREACT_EENERGY_START + EEPROM_FORWARD_INDUCTIVEREACTIVEENERGY_SIZE)
#define EEPROM_RWS_CAPREACT_EENERGY_START    EEPROM_FWD_INDREACT_EENERGY_END
#define EEPROM_RWS_CAPREACT_EENERGY_END      (EEPROM_RWS_CAPREACT_EENERGY_START + EEPROM_REVERSE_CAPACITIVEREACTIVEENERGY_SIZE)
#define EEPROM_ABS_REACT_ENERGY_START    EEPROM_RWS_CAPREACT_EENERGY_END
#define EEPROM_ABS_REACT_ENERGY_END      (EEPROM_ABS_REACT_ENERGY_START + EEPROM_ABSOLUTEREACTIVEENERGY_SIZE)
#define EEPROM_MTRING_STATUS_START    EEPROM_ABS_REACT_ENERGY_END
#define EEPROM_MTRING_STATUS_END      (EEPROM_MTRING_STATUS_START + EEPROM_METERINGSTATUS_SIZE)

#define EEPROM_L_LINE_CURRENTRMS_START    EEPROM_MTRING_STATUS_END+5
#define EEPROM_L_LINE_CURRENTRMS_END      (EEPROM_L_LINE_CURRENTRMS_START + EEPROM_L_LINECURRENTRMS_SIZE)
#define EEPROM_VOLTAGE_RMS_START    EEPROM_L_LINE_CURRENTRMS_END
#define EEPROM_VOLTAGE_RMS_END      (EEPROM_VOLTAGE_RMS_START + EEPROM_VOLTAGERMS_SIZE)
#define EEPROM_L_LINE_MEANACT_POWER_START    EEPROM_VOLTAGE_RMS_END
#define EEPROM_L_LINE_MEANACT_POWER_END      (EEPROM_L_LINE_MEANACT_POWER_START + EEPROM_L_LINEMEANACTIVEPOWER_SIZE)
#define EEPROM_L_LINE_MEANREACT_POWER_START    EEPROM_L_LINE_MEANACT_POWER_END
#define EEPROM_L_LINE_MEANREACT_POWER_END      (EEPROM_L_LINE_MEANREACT_POWER_START + EEPROM_L_LINEMEANREACTIVEPOWER_SIZE)
#define EEPROM_VOLTAGE_FREQUENCY_START    EEPROM_L_LINE_MEANREACT_POWER_END
#define EEPROM_VOLTAGE_FREQUENCY_POWER_END      (EEPROM_VOLTAGE_FREQUENCY_START + EEPROM_VOLTAGEFREQUENCY_SIZE)
#define EEPROM_L_LINE_PWR_FACTOR_START    EEPROM_VOLTAGE_FREQUENCY_POWER_END
#define EEPROM_L_LINE_PWR_FACTOR_END      (EEPROM_L_LINE_PWR_FACTOR_START + EEPROM_L_LINEPOWERFACTOR_SIZE)
#define EEPROM_PH_ANG_VOL_L_CUR_START    EEPROM_L_LINE_PWR_FACTOR_END
#define EEPROM_PH_ANG_VOL_L_CUR_END      (EEPROM_PH_ANG_VOL_L_CUR_START + EEPROM_PHASEANGLEBETWEENVOLTAGEANDL_LINECURRENT_SIZE)
#define EEPROM_L_LINE_MEANAP_PWR_START    EEPROM_PH_ANG_VOL_L_CUR_END
#define EEPROM_L_LINE_MEANAPP_PWR_END      (EEPROM_L_LINE_MEANAP_PWR_START + EEPROM_L_LINEMEANAPPARENTPOWER_SIZE)
#define EEPROM_N_LINE_CURRENTRMS_START    EEPROM_L_LINE_MEANAPP_PWR_END
#define EEPROM_N_LINE_CURRENTRMS_END      (EEPROM_N_LINE_CURRENTRMS_START + EEPROM_N_LINECURRENTRMS_SIZE)
#define EEPROM_N_LINE_MEANACT_POWER_START    EEPROM_N_LINE_CURRENTRMS_END
#define EEPROM_N_LINE_MEANACT_POWER_END      (EEPROM_N_LINE_MEANACT_POWER_START + EEPROM_N_LINEMEANACTIVEPOWER_SIZE)
#define EEPROM_N_LINE_MEAN_REACT_POWER_START    EEPROM_N_LINE_MEANACT_POWER_END
#define EEPROM_N_LINE_MEAN_REACT_POWER_END      (EEPROM_N_LINE_MEAN_REACT_POWER_START + EEPROM_N_LINEMEANREACTIVEPOWER_SIZE)
#define EEPROM_N_LINE_PWR_FACTOR_START    EEPROM_N_LINE_MEAN_REACT_POWER_END
#define EEPROM_N_LINE_PWR_FACTOR_END     (EEPROM_N_LINE_PWR_FACTOR_START + EEPROM_N_LINEPOWERFACTOR_SIZE)
#define EEPROM_PH_ANG_VOL_N_CUR_START    EEPROM_N_LINE_PWR_FACTOR_END
#define EEPROM_PH_ANG_VOL_N_CUR_END     (EEPROM_PH_ANG_VOL_N_CUR_START + EEPROM_PHASEANGLEBETWEENVOLTAGEANDN_LINECURRENT_SIZE)
#define EEPROM_N_LINE_MEANAP_PWR_START    EEPROM_PH_ANG_VOL_N_CUR_END
#define EEPROM_N_LINE_MEANAP_PWR_END     (EEPROM_N_LINE_MEANAP_PWR_START + EEPROM_N_LINEMEANAPPARENTPOWER_SIZE)

#define EEPROM_TEMPERATURE_START    EEPROM_N_LINE_MEANAP_PWR_END+5
#define EEPROM_TEMPERATURE_END     (EEPROM_TEMPERATURE_START + EEPROM_TEMPERATURE_SIZE)
#define EEPROM_TEMPERATURE_F_START    EEPROM_TEMPERATURE_END
#define EEPROM_TEMPERATURE_F_END     (EEPROM_TEMPERATURE_F_START + EEPROM_TEMPERATURE_F_SIZE)
#define EEPROM_HUMIDITY_START    EEPROM_TEMPERATURE_F_END
#define EEPROM_HUMIDITY_END     (EEPROM_HUMIDITY_START + EEPROM_HUMIDITY_SIZE)
#define EEPROM_HEATINDEX_TEMP_START    EEPROM_HUMIDITY_END
#define EEPROM_HEATINDEX_TEMP_END     (EEPROM_HEATINDEX_TEMP_START + EEPROM_HEATINDEX_TEMP_SIZE)
#define EEPROM_HEATINDEX_TEMPF_START    EEPROM_HEATINDEX_TEMP_END
#define EEPROM_HEATINDEX_TEMPF_END     (EEPROM_HEATINDEX_TEMPF_START + EEPROM_HEATINDEX_HUM_SIZE)





#ifdef SOLAR_METER
#define EEPROM_CAL_SVOLTAGE_START EEPROM_CAL_GAIN_END
#define EEPROM_CAL_SVOLTAGE_END   (EEPROM_CAL_SVOLTAGE_START + EEPROM_CAL_SVOLTAGE_SIZE)
#define EEPROM_CAL_SCT1_START     EEPROM_CAL_SVOLTAGE_END
#define EEPROM_CAL_SCT1_END       (EEPROM_CAL_SCT1_START + EEPROM_CAL_SCT1_SIZE)
#define EEPROM_CAL_SCT2_START     EEPROM_CAL_SCT1_END
#define EEPROM_CAL_SCT2_END       (EEPROM_CAL_SCT2_START + EEPROM_CAL_SCT2_SIZE)
#define EEPROM_CONFIG_END         EEPROM_CAL_SCT2_END
#else
#define EEPROM_CONFIG_END         EEPROM_HEATINDEX_TEMPF_END
#endif

#if EEPROM_CONFIG_END > EEPROM_SIZE
#error EEPROM_SIZE too small
#endif

#define CHECKSUM_SEED 128


// -------------------------------------------------------------------
